services:
  backend-service:
    build: ./backend
    container_name: backend-service
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_PORT=5432
      - DB_NAME=app_db
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - app_net
    volumes:
      - ./backend:/app
  postgresql:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge